# Generated by Django 3.2.7 on 2021-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
    ]
